# Generated by Django 4.1.3 on 2022-11-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя Автора')),
                ('email', models.EmailField(max_length=50, verbose_name='Почта')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дата Выполнения')),
                ('edit_time', models.DateField(blank=True, null=True, verbose_name='Время Изменения')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default=[('active', 'Активно'), ('blocked', 'Заблокировано')], max_length=25, verbose_name='Статус')),
            ],
        ),
    ]
